name: Run Tests

on: 
  push:
    branches:
      - main  # Здесь вы можете указать любые ветки, например, 'main' или 'develop'
  pull_request:
    branches:
      - main  # При создании PR на 'main'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Клонируем репозиторий
      - name: Checkout code
        uses: actions/checkout@v4

      # Шаг 2: Устанавливаем Node.js (версия 20.x)
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Шаг 3: Устанавливаем зависимости
      - name: Install dependencies
        run: npm install --legacy-peer-deps

      # Шаг 4: Запускаем Jest тесты
      - name: Run Jest tests
        run: npm test

      # Шаг 5: Настройка для Detox (если требуется запуск Detox для iOS или Android)
      - name: Set up Detox dependencies (optional for Android/iOS simulators)
        run: |
          npm install -g detox-cli
          npm run detox:build  # Строим приложение для тестов Detox
          npm run detox:test   # Запускаем тесты Detox
        continue-on-error: false  # Тесты не должны продолжаться, если E2E тесты не прошли
